import { useCallback, useEffect, useState } from "react";

import { ApiError, api, type ResumeDocument } from "../api";
import { EmptyState, LoadingState } from "./AsyncState";

export function ResumeIntelligence({ token, onChanged }: { token: string; onChanged: () => void }) {
  const [resumes, setResumes] = useState<ResumeDocument[] | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { try { setResumes((await api.resumes(token)).items); } catch (caught) { setMessage(caught instanceof ApiError ? caught.detail : "Resumes could not be loaded."); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  async function upload() { if (!file) return; try { const result = await api.uploadResume(file, token); setMessage(result.parse_status === "unsupported" ? result.safe_error_message : "Resume uploaded. Parse it to create evidence."); await load(); } catch (caught) { setMessage(caught instanceof ApiError ? caught.detail : "Resume upload failed."); } }
  async function parse(id: string) { try { const result = await api.parseResume(id, token); setMessage(result.safe_error_message ?? "Resume parsed. Evidence was generated and skills are extracting."); await load(); onChanged(); } catch (caught) { setMessage(caught instanceof ApiError ? caught.detail : "Resume parsing failed."); } }
  async function activate(id: string) { try { await api.activateResume(id, token); await load(); } catch (caught) { setMessage(caught instanceof ApiError ? caught.detail : "Could not activate resume."); } }
  async function remove(resume: ResumeDocument) { if (!window.confirm(`Delete ${resume.original_filename}?`)) return; try { await api.deleteResume(resume.id, token); await load(); } catch (caught) { setMessage(caught instanceof ApiError ? caught.detail : "Delete generated evidence before deleting this resume."); } }
  return <section className="rounded-xl bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold">Resume intelligence</h2><p className="mt-1 text-sm text-slate-600">PDF and DOCX only. Resume claims become evidence before they can affect your passport.</p><div className="mt-3 flex flex-wrap gap-2"><input aria-label="Resume file" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><button disabled={!file} type="button" onClick={() => void upload()} className="rounded bg-indigo-600 px-3 py-1.5 text-sm font-medium text-white disabled:bg-indigo-300">Upload resume</button></div>{message && <p role="status" className="mt-3 text-sm text-slate-600">{message}</p>}{!resumes ? <LoadingState label="Loading resumes" /> : resumes.length ? <ul className="mt-4 space-y-3">{resumes.map((resume) => <li key={resume.id} className="rounded border border-slate-200 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{resume.original_filename} {resume.is_active && <span className="text-sm text-emerald-700">Active</span>}</p><p className="text-sm text-slate-600">Resume Parsed: {resume.parse_status} · Evidence Generated: {resume.generated_evidence_count} · Skills: {resume.skills_status}</p></div><div className="flex gap-2 text-sm"><button type="button" onClick={() => void parse(resume.id)} disabled={resume.parse_status === "unsupported"} className="text-indigo-700 disabled:text-slate-400">Parse</button><button type="button" onClick={() => void activate(resume.id)} className="text-indigo-700">Activate</button><button type="button" onClick={() => void remove(resume)} className="text-red-700">Delete</button></div></div>{resume.safe_error_message && <p className="mt-2 text-sm text-amber-700">{resume.safe_error_message}</p>}{resume.parsed_summary && <p className="mt-2 text-sm text-slate-600">Projects: {resume.parsed_summary.projects.length} · Certifications: {resume.parsed_summary.certifications.length} · Explicit skills: {resume.parsed_summary.explicit_technical_skills.join(", ") || "none"}</p>}</li>)}</ul> : <EmptyState title="No resume uploaded">Upload a text-based PDF or DOCX to generate evidence.</EmptyState>}</section>;
}
