import { request } from "./client";
import type {
  Application, ApplicationForm, ApplicationStatusEvent, ApplicationSubmissionAttempt, AuthSession, CandidateMatch, CandidateProfile, EvidenceDetail, EvidenceSubmission, EvidenceSummary, EvidenceUpdate, ExternalJob, ExternalJobMatch, Internship, InternshipCreate, InternshipUpdate, JobDiscovery, JobDiscoveryRun,
  LoginRequest, MatchExplanation, PaginatedResponse, Passport, RecruiterRegistration, Skill,
  StudentMatch, StudentRegistration, TeamSuggestion, TeamSuggestionRequest, VerificationResult, RecruiterEvidenceConsent, GitHubIdentity, ResumeDocument,
} from "./types";

export const api = {
  registerStudent: (input: StudentRegistration) => request<AuthSession>("/auth/register/student", { method: "POST", body: JSON.stringify(input) }),
  registerRecruiter: (input: RecruiterRegistration) => request<AuthSession>("/auth/register/recruiter", { method: "POST", body: JSON.stringify(input) }),
  login: (input: LoginRequest) => request<AuthSession>("/auth/login", { method: "POST", body: JSON.stringify(input) }),
  passport: (token: string) => request<Passport>("/passport/me", {}, token),
  candidateProfile: (token: string) => request<CandidateProfile>("/passport/profile", {}, token),
  submitEvidence: (input: EvidenceSubmission, token: string) => request<EvidenceSummary>("/evidence", { method: "POST", body: JSON.stringify(input) }, token),
  evidence: (id: string, token: string) => request<EvidenceDetail>(`/evidence/${encodeURIComponent(id)}`, {}, token),
  evidences: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<EvidenceSummary>>(`/evidence?page=${page}&page_size=${pageSize}`, {}, token),
  updateEvidence: (id: string, input: EvidenceUpdate, token: string) => request<EvidenceDetail>(`/evidence/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(input) }, token),
  deleteEvidence: (id: string, token: string) => request<void>(`/evidence/${encodeURIComponent(id)}`, { method: "DELETE" }, token),
  resumes: (token: string) => request<PaginatedResponse<ResumeDocument>>("/resumes", {}, token),
  uploadResume: (file: File, token: string) => { const body = new FormData(); body.append("file", file); return request<ResumeDocument>("/resumes", { method: "POST", body }, token); },
  parseResume: (id: string, token: string) => request<ResumeDocument>(`/resumes/${encodeURIComponent(id)}/parse`, { method: "POST" }, token),
  activateResume: (id: string, token: string) => request<ResumeDocument>(`/resumes/${encodeURIComponent(id)}/activate`, { method: "PUT" }, token),
  deleteResume: (id: string, token: string) => request<void>(`/resumes/${encodeURIComponent(id)}`, { method: "DELETE" }, token),
  requeueEvidence: (id: string, token: string) => request<EvidenceDetail>(`/evidence/${encodeURIComponent(id)}/requeue`, { method: "POST" }, token),
  verifyEvidence: (id: string, token: string) => request<VerificationResult>(`/evidence/${encodeURIComponent(id)}/verify`, { method: "POST", body: JSON.stringify({ check_type: "github_project" }) }, token),
  searchSkills: (query: string, token: string) => request<Skill[]>(`/skills/search?q=${encodeURIComponent(query)}`, {}, token),
  createInternship: (input: InternshipCreate, token: string) => request<Internship>("/internships", { method: "POST", body: JSON.stringify(input) }, token),
  internship: (id: string, token: string) => request<Internship>(`/internships/${encodeURIComponent(id)}`, {}, token),
  updateInternship: (id: string, input: InternshipUpdate, token: string) => request<Internship>(`/internships/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(input) }, token),
  deleteInternship: (id: string, token: string) => request<void>(`/internships/${encodeURIComponent(id)}`, { method: "DELETE" }, token),
  internshipMatches: (id: string, token: string, page = 1, pageSize = 20) => request<PaginatedResponse<CandidateMatch>>(`/internships/${encodeURIComponent(id)}/matches?page=${page}&page_size=${pageSize}`, {}, token),
  internships: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<Internship>>(`/internships?page=${page}&page_size=${pageSize}`, {}, token),
  externalJobs: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<ExternalJob>>(`/external-jobs?page=${page}&page_size=${pageSize}`, {}, token),
  externalJobMatches: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<ExternalJobMatch>>(`/external-jobs/matches?page=${page}&page_size=${pageSize}`, {}, token),
  recomputeExternalJobMatches: (token: string) => request<ExternalJobMatch[]>("/external-jobs/matches/recompute", { method: "POST" }, token),
  applications: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<Application>>(`/applications?page=${page}&page_size=${pageSize}`, {}, token),
  createApplication: (externalJobId: string, externalJobMatchId: string, token: string) => request<Application>("/applications", { method: "POST", body: JSON.stringify({ external_job_id: externalJobId, external_job_match_id: externalJobMatchId }) }, token),
  requestApplicationApproval: (id: string, token: string) => request<Application>(`/applications/${encodeURIComponent(id)}/request-approval`, { method: "POST" }, token),
  approveApplication: (id: string, token: string) => request<Application>(`/applications/${encodeURIComponent(id)}/approve`, { method: "POST" }, token),
  revokeApplicationApproval: (id: string, token: string) => request<Application>(`/applications/${encodeURIComponent(id)}/revoke-approval`, { method: "POST" }, token),
  selectManualApplication: (id: string, token: string) => request<Application>(`/applications/${encodeURIComponent(id)}/manual`, { method: "POST" }, token),
  withdrawApplication: (id: string, token: string) => request<Application>(`/applications/${encodeURIComponent(id)}/withdraw`, { method: "POST" }, token),
  prepareApplication: (id: string, token: string) => request<ApplicationForm>(`/applications/${encodeURIComponent(id)}/prepare`, { method: "POST" }, token),
  applicationForm: (id: string, token: string) => request<ApplicationForm>(`/applications/${encodeURIComponent(id)}/form`, {}, token),
  updateApplicationAnswers: (id: string, answers: Record<string, unknown>, token: string) => request<ApplicationForm>(`/applications/${encodeURIComponent(id)}/answers`, { method: "PUT", body: JSON.stringify({ answers }) }, token),
  readyApplication: (id: string, token: string) => request<Application>(`/applications/${encodeURIComponent(id)}/ready`, { method: "POST" }, token),
  submitApplication: (id: string, token: string) => request<Application>(`/applications/${encodeURIComponent(id)}/submit`, { method: "POST" }, token),
  applicationTimeline: (id: string, token: string) => request<ApplicationStatusEvent[]>(`/applications/${encodeURIComponent(id)}/timeline`, {}, token),
  applicationAttempts: (id: string, token: string) => request<ApplicationSubmissionAttempt[]>(`/applications/${encodeURIComponent(id)}/attempts`, {}, token),
  markManualSubmission: (id: string, token: string, input: { submitted_at?: string; provider_reference?: string }) => request<Application>(`/applications/${encodeURIComponent(id)}/mark-manual-submitted`, { method: "POST", body: JSON.stringify(input) }, token),
  reconcileApplication: (id: string, token: string) => request<Application>(`/applications/${encodeURIComponent(id)}/reconcile`, { method: "POST" }, token),
  jobDiscoveries: (token: string) => request<PaginatedResponse<JobDiscovery>>("/job-discoveries", {}, token),
  createJobDiscovery: (input: Omit<JobDiscovery, "id" | "student_id" | "last_run_at" | "next_run_at" | "created_at" | "updated_at">, token: string) => request<JobDiscovery>("/job-discoveries", { method: "POST", body: JSON.stringify(input) }, token),
  updateJobDiscovery: (id: string, input: Partial<JobDiscovery>, token: string) => request<JobDiscovery>(`/job-discoveries/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(input) }, token),
  deleteJobDiscovery: (id: string, token: string) => request<void>(`/job-discoveries/${encodeURIComponent(id)}`, { method: "DELETE" }, token),
  runJobDiscovery: (id: string, token: string) => request<JobDiscoveryRun>(`/job-discoveries/${encodeURIComponent(id)}/run`, { method: "POST" }, token),
  jobDiscoveryRuns: (id: string, token: string) => request<PaginatedResponse<JobDiscoveryRun>>(`/job-discoveries/${encodeURIComponent(id)}/runs`, {}, token),
  studentMatches: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<StudentMatch>>(`/students/me/matches?page=${page}&page_size=${pageSize}`, {}, token),
  recomputeStudentMatches: (token: string) => request<StudentMatch[]>("/students/me/matches/recompute", { method: "POST" }, token),
  recomputeInternshipMatches: (id: string, token: string) => request<CandidateMatch[]>(`/internships/${encodeURIComponent(id)}/matches/recompute`, { method: "POST" }, token),
  explanation: (id: string, token: string) => request<MatchExplanation>(`/matches/${encodeURIComponent(id)}/explanation`, {}, token),
  recruiterEvidenceConsent: (token: string) => request<RecruiterEvidenceConsent>("/passport/consent", {}, token),
  setRecruiterEvidenceConsent: (recruiterEvidenceConsent: boolean, token: string) => request<RecruiterEvidenceConsent>("/passport/consent", { method: "PUT", body: JSON.stringify({ recruiter_evidence_consent: recruiterEvidenceConsent }) }, token),
  githubIdentity: (token: string) => request<GitHubIdentity>("/passport/github-identity", {}, token),
  setGithubIdentity: (githubUsername: string, token: string) => request<GitHubIdentity>("/passport/github-identity", { method: "PUT", body: JSON.stringify({ github_username: githubUsername }) }, token),
  suggestTeams: (input: TeamSuggestionRequest, token: string) => request<TeamSuggestion[]>("/teams/suggest", { method: "POST", body: JSON.stringify(input) }, token),
};
