import { request } from "./client";
import type {
  AuthSession, CandidateMatch, CandidateProfile, EvidenceDetail, EvidenceSubmission, EvidenceSummary, EvidenceUpdate, Internship, InternshipCreate, InternshipUpdate,
  LoginRequest, MatchExplanation, PaginatedResponse, Passport, RecruiterRegistration, Skill,
  StudentMatch, StudentRegistration, TeamSuggestion, TeamSuggestionRequest, VerificationResult, RecruiterEvidenceConsent, GitHubIdentity, ResumeDocument,
} from "./types";

export const api = {
  registerStudent: (input: StudentRegistration) => request<AuthSession>("/auth/register/student", { method: "POST", body: JSON.stringify(input) }),
  registerRecruiter: (input: RecruiterRegistration) => request<AuthSession>("/auth/register/recruiter", { method: "POST", body: JSON.stringify(input) }),
  login: (input: LoginRequest) => request<AuthSession>("/auth/login", { method: "POST", body: JSON.stringify(input) }),
  passport: (token: string) => request<Passport>("/passport/me", {}, token),
  candidateProfile: (token: string) => request<CandidateProfile>("/passport/profile", {}, token),
  submitEvidence: (input: EvidenceSubmission, token: string) => request<EvidenceSummary>("/evidence", { method: "POST", body: JSON.stringify(input) }, token),
  evidence: (id: string, token: string) => request<EvidenceDetail>(`/evidence/${encodeURIComponent(id)}`, {}, token),
  evidences: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<EvidenceSummary>>(`/evidence?page=${page}&page_size=${pageSize}`, {}, token),
  updateEvidence: (id: string, input: EvidenceUpdate, token: string) => request<EvidenceDetail>(`/evidence/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(input) }, token),
  deleteEvidence: (id: string, token: string) => request<void>(`/evidence/${encodeURIComponent(id)}`, { method: "DELETE" }, token),
  resumes: (token: string) => request<PaginatedResponse<ResumeDocument>>("/resumes", {}, token),
  uploadResume: (file: File, token: string) => { const body = new FormData(); body.append("file", file); return request<ResumeDocument>("/resumes", { method: "POST", body }, token); },
  parseResume: (id: string, token: string) => request<ResumeDocument>(`/resumes/${encodeURIComponent(id)}/parse`, { method: "POST" }, token),
  activateResume: (id: string, token: string) => request<ResumeDocument>(`/resumes/${encodeURIComponent(id)}/activate`, { method: "PUT" }, token),
  deleteResume: (id: string, token: string) => request<void>(`/resumes/${encodeURIComponent(id)}`, { method: "DELETE" }, token),
  requeueEvidence: (id: string, token: string) => request<EvidenceDetail>(`/evidence/${encodeURIComponent(id)}/requeue`, { method: "POST" }, token),
  verifyEvidence: (id: string, token: string) => request<VerificationResult>(`/evidence/${encodeURIComponent(id)}/verify`, { method: "POST", body: JSON.stringify({ check_type: "github_project" }) }, token),
  searchSkills: (query: string, token: string) => request<Skill[]>(`/skills/search?q=${encodeURIComponent(query)}`, {}, token),
  createInternship: (input: InternshipCreate, token: string) => request<Internship>("/internships", { method: "POST", body: JSON.stringify(input) }, token),
  internship: (id: string, token: string) => request<Internship>(`/internships/${encodeURIComponent(id)}`, {}, token),
  updateInternship: (id: string, input: InternshipUpdate, token: string) => request<Internship>(`/internships/${encodeURIComponent(id)}`, { method: "PATCH", body: JSON.stringify(input) }, token),
  deleteInternship: (id: string, token: string) => request<void>(`/internships/${encodeURIComponent(id)}`, { method: "DELETE" }, token),
  internshipMatches: (id: string, token: string, page = 1, pageSize = 20) => request<PaginatedResponse<CandidateMatch>>(`/internships/${encodeURIComponent(id)}/matches?page=${page}&page_size=${pageSize}`, {}, token),
  internships: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<Internship>>(`/internships?page=${page}&page_size=${pageSize}`, {}, token),
  studentMatches: (token: string, page = 1, pageSize = 20) => request<PaginatedResponse<StudentMatch>>(`/students/me/matches?page=${page}&page_size=${pageSize}`, {}, token),
  recomputeStudentMatches: (token: string) => request<StudentMatch[]>("/students/me/matches/recompute", { method: "POST" }, token),
  recomputeInternshipMatches: (id: string, token: string) => request<CandidateMatch[]>(`/internships/${encodeURIComponent(id)}/matches/recompute`, { method: "POST" }, token),
  explanation: (id: string, token: string) => request<MatchExplanation>(`/matches/${encodeURIComponent(id)}/explanation`, {}, token),
  recruiterEvidenceConsent: (token: string) => request<RecruiterEvidenceConsent>("/passport/consent", {}, token),
  setRecruiterEvidenceConsent: (recruiterEvidenceConsent: boolean, token: string) => request<RecruiterEvidenceConsent>("/passport/consent", { method: "PUT", body: JSON.stringify({ recruiter_evidence_consent: recruiterEvidenceConsent }) }, token),
  githubIdentity: (token: string) => request<GitHubIdentity>("/passport/github-identity", {}, token),
  setGithubIdentity: (githubUsername: string, token: string) => request<GitHubIdentity>("/passport/github-identity", { method: "PUT", body: JSON.stringify({ github_username: githubUsername }) }, token),
  suggestTeams: (input: TeamSuggestionRequest, token: string) => request<TeamSuggestion[]>("/teams/suggest", { method: "POST", body: JSON.stringify(input) }, token),
};
